version: 0.0
os: linux
files:
  - source: ./**/*
    destination: /home/ubuntu/som-api-apollo-graphqlapi/*

  - source: ./deploy/files/som-api-graphql.service
    destination: /lib/systemd/system/

  - source: ./deploy/files/nginx.config
    destination: /etc/nginx/sites-enabled/default

hooks:
  BeforeInstall:
    - location: ./deploy/scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./deploy/scripts/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./deploy/scripts/application_start.sh
      timeout: 300
      runas: root