version: 0.2

phases:
  install:
    commands:
      - echo Initalling source NPM depencies
      - yarn
  pre_build:
    commands:
      - npm nx --version

  build:
    commands:
      - echo Projects build started on `date`
      - echo Using variables
      - echo NODE_ENV = $NODE_ENV

      # Run Tests
      # - echo Backend build started on `date`
      # - npm run test:gt:runs

      # Delete node_modules
      - rm -rf node_modules

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    graphql-api:
      files:
        - '**/*'
    blah:
      files:
        - '**/*'
