version: 0.2

phases:
  install:
    commands:
      - echo Initalling source NPM depencies
      - yarn
  pre_build:
    commands:
      - npm nx --version

  build:
    commands:
      - echo Projects build started on `date`
      - echo Using variables
      - echo NODE_ENV = $NODE_ENV

      # Run Tests
      # - echo Backend build started on `date`
      # - npm run test:gt:runs

      # Building backend
      - echo Backend build started on `date`
      - yarn build

      - echo Backend build completed on `date`

      # Creating deploy folder
      - mkdir athentication-api
      
      # populate dist into deploy folder
      - mkdir athentication-api/dist
      - cp -r dist/* athentication-api/dist/
      
      # Populate scripts into deploy folder
      - mkdir athentication-api/scripts
      - cp -r deploy/scripts/* athentication-api/scripts/
    
      # Populate server files into deploy folder
      - mkdir athentication-api/server-files
      - cp -r deploy/files/ida-authentication-api.service athentication-api/server-files/ida-authentication-api.service
      - cp -r deploy/files/nginx.config athentication-api/server-files/default
      
      # Get config files
      - cp package.json ./athentication-api/package.json
      - cp appspec.yml ./athentication-api/appspec.yml

      # Delete node_modules
      - rm -rf node_modules

      # List backck and frontend folders
      - ls ./athentication-api

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    athentication:
      files:
        - '**/*'
      base-directory: athentication-api
    blah:
      files:
        - '**/*'
      base-directory: athentication-api
